### ISSUE TITLE
type prometheus.Counter has no field or method Set

### ISSUE THREAD

**Issue by israelriibeiro** [neezgee/apache_exporter#14]
Hi, Guys. 

I'm using debian 8.2( jessie) and apache 2.4.10, and i added apache mod status.
And i'm using ExtendedStatus On, which enables a lot of variables on status page. But when i run go run apache_exporter, in order to test this, i got this result:

```
# command-line-arguments
./apache_exporter.go:194: e.accessesTotal.Set undefined (type prometheus.Counter has no field or method Set)
./apache_exporter.go:202: e.kBytesTotal.Set undefined (type prometheus.Counter has no field or method Set)
./apache_exporter.go:210: e.uptime.Set undefined (type prometheus.Counter has no field or method Set)

```

Thanks in advance.

**Comment by neezgee** [comment]
Hi! It must be fixed by ton31337.

Thanks for report!
