### ISSUE TITLE
Not only did apache_exporter  monitored 80 port, but also it monitors other ports ?

### ISSUE THREAD

**Issue by dk900912** [neezgee/apache_exporter#24]
And when i startup apache_exporter, it comes with 'The requested URL /server-status/ was not found on this server.'

**Comment by neezgee** [comment]
What url did you specify in -scrape_uri? Can you access it with, lets say, curl?

**Comment by dk900912** [comment]
-scrape-uri='http://localhost:8686/server-status/
![image](https://user-images.githubusercontent.com/12511399/29394397-78caa15e-833c-11e7-8061-cb8982b2dbd1.png)

**Comment by dk900912** [comment]
Hi, Zeengee! Can u privide a complete metrics list of apache 2.4+ for me ? Appreciated!! Why I can not extract apache_connections、apache_sent_kilobytes_total···
![image](https://user-images.githubusercontent.com/12511399/29404158-ee2a69a4-836c-11e7-8428-4230990dfdd2.png)

**Comment by neezgee** [comment]
Sorry, this is definitely a problem with apache/exporter configuration.

If you really need additional metrics, try to leave a feature request. I'll not have time to implement it though, but maybe someone else can do it.

**Comment by dk900912** [comment]
I have solved this problem ! thank u
