### ISSUE TITLE
Error scraping apache: strconf.ParseFloat

### ISSUE THREAD

**Issue by gerardbos** [neezgee/apache_exporter#7]
Contstantly getting the error: 
INFO[0020] Error scraping apache: strconv.ParseFloat: parsing "": invalid syntax  file=apache_exporter.go line=156

Startup command is: 
./apache_exporter -log.level debug -scrape_uri "https://my.domain.name/server-status?auto"

The output of the server-status is: 
> my.domain.name
> ServerVersion: Apache/2.4.23 (Unix) OpenSSL/1.0.2h
> ServerMPM: worker
> Server Built: Aug 31 2016 10:54:08
> CurrentTime: Thursday, 08-Sep-2016 15:09:32 CEST
> RestartTime: Thursday, 08-Sep-2016 15:08:07 CEST
> ParentServerConfigGeneration: 1
> ParentServerMPMGeneration: 0
> ServerUptimeSeconds: 85
> ServerUptime: 1 minute 25 seconds
> Load1: 0.00
> Load5: 0.01
> Load15: 0.05
> Total Accesses: 10
> Total kBytes: 38
> CPUUser: .05
> CPUSystem: 0
> CPUChildrenUser: 0
> CPUChildrenSystem: 0
> CPULoad: .0588235
> Uptime: 85
> ReqPerSec: .117647
> BytesPerSec: 457.788
> BytesPerReq: 3891.2
> BusyWorkers: 2
> IdleWorkers: 48
> Scoreboard: _____R_______________________K____________________....................................................................................................
> TLSSessionCacheStatus
> CacheType: SHMCB
> CacheSharedMemory: 512000
> CacheCurrentEntries: 0
> CacheSubcaches: 32
> CacheIndexesPerSubcaches: 88
> CacheIndexUsage: 0%
> CacheUsage: 0%
> CacheStoreCount: 0
> CacheReplaceCount: 0
> CacheExpireCount: 0
> CacheDiscardCount: 0
> CacheRetrieveHitCount: 0
> CacheRetrieveMissCount: 1
> CacheRemoveHitCount: 0
> CacheRemoveMissCount: 0
>

**Comment by neezgee** [comment]
Hi! Thank you for the report. I think it must be resolved now. Can you test it with the HEAD?

**Comment by gerardbos** [comment]
I tested it and it works! Thanks!
