### ISSUE TITLE
strconv.ParseFloat: parsing \"\":

### ISSUE THREAD

**Issue by raypettersen** [neezgee/apache_exporter#8]
I'm unable to scrape apache 2.4.16

time="2016-09-09T20:13:48+02:00" level=info msg="Error scraping apache: strconv.ParseFloat: parsing \"\": invalid syntax" file="apache_exporter.go" line=156 
time="2016-09-09T20:13:54+02:00" level=info msg="Error scraping apache: strconv.ParseFloat: parsing \"\": invalid syntax" file="apache_exporter.go" line=156 
time="2016-09-09T20:14:48+02:00" level=info msg="Error scraping apache: strconv.ParseFloat: parsing \"\": invalid syntax" file="apache_exporter.go" line=156 

This is my apache output.

127.0.0.1
ServerVersion: Apache/2.4.16 (Unix) OpenSSL/1.0.2h
ServerMPM: worker
Server Built: Jul  4 2016 22:40:23
CurrentTime: Friday, 09-Sep-2016 20:19:59 CEST
RestartTime: Thursday, 08-Sep-2016 21:25:12 CEST
ParentServerConfigGeneration: 1
ParentServerMPMGeneration: 0
ServerUptimeSeconds: 82486
ServerUptime: 22 hours 54 minutes 46 seconds
Load1: 0.50
Load5: 0.17
Load15: 0.16
Total Accesses: 1508
Total kBytes: 8023
CPUUser: 1.36
CPUSystem: .61
CPUChildrenUser: 0
CPUChildrenSystem: 0
CPULoad: .00238828
Uptime: 82486
ReqPerSec: .0182819
BytesPerSec: 99.5993
BytesPerReq: 5447.98
BusyWorkers: 1
IdleWorkers: 191

**Comment by raypettersen** [comment]
Seems to be a duplicate of issue #7 ?

**Comment by neezgee** [comment]
Yes, I think it is. Can you check if the issue is resolved now?

**Comment by raypettersen** [comment]
The problem seems to be fixed:

# HELP apache_accesses_total Current total apache accesses
# TYPE apache_accesses_total counter
apache_accesses_total 5239
# HELP apache_sent_kilobytes_total Current total kbytes sent
# TYPE apache_sent_kilobytes_total counter
apache_sent_kilobytes_total 22465
# HELP apache_uptime_seconds_total Current uptime in seconds
# TYPE apache_uptime_seconds_total counter
apache_uptime_seconds_total 306161
# HELP apache_workers Apache worker statuses
# TYPE apache_workers gauge
apache_workers{state="busy"} 1
apache_workers{state="idle"} 191
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0.000344385
go_gc_duration_seconds{quantile="0.25"} 0.000344385
go_gc_duration_seconds{quantile="0.5"} 0.000344385
go_gc_duration_seconds{quantile="0.75"} 0.000344385
go_gc_duration_seconds{quantile="1"} 0.000344385
go_gc_duration_seconds_sum 0.000344385
go_gc_duration_seconds_count 1
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 11
# HELP go_memstats_alloc_bytes Number of bytes allocated and still in use.
# TYPE go_memstats_alloc_bytes gauge
go_memstats_alloc_bytes 2.459672e+06
# HELP go_memstats_alloc_bytes_total Total number of bytes allocated, even if freed.
# TYPE go_memstats_alloc_bytes_total counter
go_memstats_alloc_bytes_total 5.679048e+06
# HELP go_memstats_buck_hash_sys_bytes Number of bytes used by the profiling bucket hash table.
# TYPE go_memstats_buck_hash_sys_bytes gauge
go_memstats_buck_hash_sys_bytes 1.443391e+06
# HELP go_memstats_frees_total Total number of frees.
# TYPE go_memstats_frees_total counter
go_memstats_frees_total 6775
# HELP go_memstats_gc_sys_bytes Number of bytes used for garbage collection system metadata.
# TYPE go_memstats_gc_sys_bytes gauge
go_memstats_gc_sys_bytes 409600
# HELP go_memstats_heap_alloc_bytes Number of heap bytes allocated and still in use.
# TYPE go_memstats_heap_alloc_bytes gauge
go_memstats_heap_alloc_bytes 2.459672e+06
# HELP go_memstats_heap_idle_bytes Number of heap bytes waiting to be used.
# TYPE go_memstats_heap_idle_bytes gauge
go_memstats_heap_idle_bytes 5.070848e+06
# HELP go_memstats_heap_inuse_bytes Number of heap bytes that are in use.
# TYPE go_memstats_heap_inuse_bytes gauge
go_memstats_heap_inuse_bytes 2.99008e+06
# HELP go_memstats_heap_objects Number of allocated objects.
# TYPE go_memstats_heap_objects gauge
go_memstats_heap_objects 6756
# HELP go_memstats_heap_released_bytes_total Total number of heap bytes released to OS.
# TYPE go_memstats_heap_released_bytes_total counter
go_memstats_heap_released_bytes_total 0
# HELP go_memstats_heap_sys_bytes Number of heap bytes obtained from system.
# TYPE go_memstats_heap_sys_bytes gauge
go_memstats_heap_sys_bytes 8.060928e+06
# HELP go_memstats_last_gc_time_seconds Number of seconds since 1970 of last garbage collection.
# TYPE go_memstats_last_gc_time_seconds gauge
go_memstats_last_gc_time_seconds 1.4736688090124803e+09
# HELP go_memstats_lookups_total Total number of pointer lookups.
# TYPE go_memstats_lookups_total counter
go_memstats_lookups_total 82
# HELP go_memstats_mallocs_total Total number of mallocs.
# TYPE go_memstats_mallocs_total counter
go_memstats_mallocs_total 13531
# HELP go_memstats_mcache_inuse_bytes Number of bytes in use by mcache structures.
# TYPE go_memstats_mcache_inuse_bytes gauge
go_memstats_mcache_inuse_bytes 2400
# HELP go_memstats_mcache_sys_bytes Number of bytes used for mcache structures obtained from system.
# TYPE go_memstats_mcache_sys_bytes gauge
go_memstats_mcache_sys_bytes 16384
# HELP go_memstats_mspan_inuse_bytes Number of bytes in use by mspan structures.
# TYPE go_memstats_mspan_inuse_bytes gauge
go_memstats_mspan_inuse_bytes 25760
# HELP go_memstats_mspan_sys_bytes Number of bytes used for mspan structures obtained from system.
# TYPE go_memstats_mspan_sys_bytes gauge
go_memstats_mspan_sys_bytes 49152
# HELP go_memstats_next_gc_bytes Number of heap bytes when next garbage collection will take place.
# TYPE go_memstats_next_gc_bytes gauge
go_memstats_next_gc_bytes 4.194304e+06
# HELP go_memstats_other_sys_bytes Number of bytes used for other system allocations.
# TYPE go_memstats_other_sys_bytes gauge
go_memstats_other_sys_bytes 774841
# HELP go_memstats_stack_inuse_bytes Number of bytes in use by the stack allocator.
# TYPE go_memstats_stack_inuse_bytes gauge
go_memstats_stack_inuse_bytes 327680
# HELP go_memstats_stack_sys_bytes Number of bytes obtained from system for stack allocator.
# TYPE go_memstats_stack_sys_bytes gauge
go_memstats_stack_sys_bytes 327680
# HELP go_memstats_sys_bytes Number of bytes obtained by system. Sum of all system allocations.
# TYPE go_memstats_sys_bytes gauge
go_memstats_sys_bytes 1.1081976e+07
# HELP http_request_duration_microseconds The HTTP request latencies in microseconds.
# TYPE http_request_duration_microseconds summary
http_request_duration_microseconds{handler="prometheus",quantile="0.5"} 4074.223
http_request_duration_microseconds{handler="prometheus",quantile="0.9"} 6445.247
http_request_duration_microseconds{handler="prometheus",quantile="0.99"} 6445.247
http_request_duration_microseconds_sum{handler="prometheus"} 26186.410000000003
http_request_duration_microseconds_count{handler="prometheus"} 6
# HELP http_request_size_bytes The HTTP request sizes in bytes.
# TYPE http_request_size_bytes summary
http_request_size_bytes{handler="prometheus",quantile="0.5"} 315
http_request_size_bytes{handler="prometheus",quantile="0.9"} 315
http_request_size_bytes{handler="prometheus",quantile="0.99"} 315
http_request_size_bytes_sum{handler="prometheus"} 1638
http_request_size_bytes_count{handler="prometheus"} 6
# HELP http_requests_total Total number of HTTP requests made.
# TYPE http_requests_total counter
http_requests_total{code="200",handler="prometheus",method="get"} 6
# HELP http_response_size_bytes The HTTP response sizes in bytes.
# TYPE http_response_size_bytes summary
http_response_size_bytes{handler="prometheus",quantile="0.5"} 1424
http_response_size_bytes{handler="prometheus",quantile="0.9"} 7074
http_response_size_bytes{handler="prometheus",quantile="0.99"} 7074
http_response_size_bytes_sum{handler="prometheus"} 14089
http_response_size_bytes_count{handler="prometheus"} 6
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.03
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 4096
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 8
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 8.06912e+06
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.47366860812e+09
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 5.6070144e+07

Will you be creating a release?
